version: "3.9"
services:
  web:
    container_name: config_account
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8000
    volumes:
      - ./:/home/mobio/projects/AccountConfig
  