version: "3.9"
services:
  web:
    container_name: config-account-v1
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8000
    volumes:
      - ./:/home/mobio/projects/AccountConfig
    networks:
      - backend
 
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: config-account-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend

  kafka:
    image: bitnami/kafka:latest
    container_name: config-account-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=config-account-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - backend
  
  mongo:
    image: mongo:latest
    ports:
        - '27017:27017'
    container_name: config-account-mongo
    logging:
      options:
          max-size: 1g
    restart: always
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - backend

    
  redis:
    image: redis:latest
    container_name: config-account-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
  
networks:
  backend:

volumes:
  mongo_config_account:
  redis_config_account:
